# Generated by Django 4.2.13 on 2025-05-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
