# Generated by Django 4.2.13 on 2025-05-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_visitante_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='documento',
        ),
        migrations.AddField(
            model_name='visitante',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
