# Generated by Django 4.2.13 on 2025-05-22 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_remove_visitante_documento_visitante_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='entrada',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
