# Generated by Django 4.2.13 on 2025-05-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0004_visitante_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='entrada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
