# Generated by Django 4.2.13 on 2025-05-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_OS', models.CharField(max_length=20, unique=True)),
                ('Nome_OS', models.CharField(max_length=50)),
                ('Descricao_OS', models.TextField()),
                ('Profissional_responsavel', models.CharField(max_length=100)),
                ('Empresa_responsável', models.CharField(max_length=100)),
                ('data_servico', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_saida', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='OrdemDeServico',
        ),
    ]
