# Generated by Django 4.2.13 on 2025-06-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresas',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
