# Generated by Django 4.2.13 on 2025-05-20 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('empresa', models.CharField(max_length=50)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='visitantes.visitante')),
            ],
        ),
        migrations.DeleteModel(
            name='Visitas',
        ),
    ]
