# Generated by Django 4.2.13 on 2025-05-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_visita_delete_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
    ]
