# Generated by Django 4.2.13 on 2025-06-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_alter_visita_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='ordem_de_servico',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
